//////////////////////////////////////////////////////////////////////////////
// Model: fsa_eos.qm
// File:  ./bsp.h
//
// This file has been generated automatically by QP Modeler (QM).
// DO NOT EDIT THIS FILE MANUALLY.
//
// Please visit www.state-machine.com/qm for more information.
//////////////////////////////////////////////////////////////////////////////
/* Focus Stacking Assistant bsp header */

#ifndef bsp_h
#define bsp_h

#include <avr/io.h>
#include "Wprogram.h"
#include <message.h>                                                // AVR I/O

                                                 // Sys timer tick per seconds
#define BSP_TICKS_PER_SEC    100


void BSP_init(void);


//////////////////////////////////////////////////////////////////////////////
// NOTE: The CPU clock frequency F_CPU is defined externally for each
// Arduino board

#endif                                                                // bsp_h



