//////////////////////////////////////////////////////////////////////////////
// Model: fsa_eos.qm
// File:  ./fsa.h
//
// This file has been generated automatically by QP Modeler (QM).
// DO NOT EDIT THIS FILE MANUALLY.
//
// Please visit www.state-machine.com/qm for more information.
//////////////////////////////////////////////////////////////////////////////
/* Focus Stacking Assistant main header */

#ifndef fsa_h
#define fsa_h

#include "Usb.h"

enum FsaSignals {
    //controller signals
    FOCUS_MOVED_SIG = Q_USER_SIG,    //near step
    NEAR_STEP_SIG,
    FAR_STEP_SIG,
    //MAX_PUB_SIG,
    CAPTURE_SIG,
    //CMD_COMPLETE_SIG,
    FM_COMPLETE_SIG,
    FM_ERROR_SIG,
    CAP_COMPLETE_SIG,
    NEAR_SET_SIG,
    FAR_SET_SIG,
    RUN_SIG,
    FREERUN_SIG,
    SHOOT_SIG,
    //button signals
    N_PRESS_SIG,
    N_RELEASE_SIG,
    N_TIMEOUT_SIG,
    F_PRESS_SIG,               //far
    F_RELEASE_SIG,
    F_TIMEOUT_SIG,
    G_PRESS_SIG,               //go
    G_RELEASE_SIG,
    G_TIMEOUT_SIG,
    LP_TIMEOUT_SIG,
    //camera signals
    CAM_READY_SIG,
    CAM_DISC_SIG,
    //LED signals
    LED_IDLE_SIG,
    LED_WORKING_SIG,
    LED_ERROR_SIG,
    LED_PER_TIMEOUT_SIG,
    LED_ON_TIMEOUT_SIG,
    LED_WORK_TIMEOUT_SIG,
    LED_TIMEOUT_SIG,
    USB_TICK_SIG,
    CMD_DELAY_SIG,
    CAP_DELAY_SIG,
    /**/
    MAX_SIG
};


#define LED_ON()      (PORTB |= (1 << (0)))
#define LED_OFF()     (PORTB &= ~(1 << (0)))

//focus step commands
#define N_STEP1 0x0001
#define N_STEP2 0x0002
#define N_STEP3 0x0003
#define F_STEP1 0x8001
#define F_STEP2 0x8002
#define F_STEP3 0x8003

/* redefine lens motor step here */
#define NSTEP N_STEP2
#define FSTEP F_STEP2

// $(Events::FocusMovedEvt) ..................................................
class FocusMovedEvt : public QEvent {
public:
    uint16_t focus_position;
};

// active objects ............................................................
extern QActive * const AO_Controls;    // "opaque" pointer to Controls AO
extern QActive * const AO_Camera;      //"opaque" pointer to Camera AO
extern QActive * const AO_Lights;        //"opaque" pointer to Lights AO
extern QActive * const AO_Usbtask;        //"opaque" pointer to Usbtask AO
extern QActive * const AO_Commands;        //"opaque" pointer to Commands AO
extern USB* const O_usb;            //pointer to Usb


#endif                                                            // fsa_h

